org.gradle.jvmargs=-Xmx4G
org.gradle.parallel=true

# Fabric Properties
# check these on https://fabricmc.net/develop
minecraft_version=26.1.2
loader_version=0.19.5
loom_version=1.17.21
kotlin_version=2.4.20
fabric_kotlin_version=1.14.1+kotlin.2.4.20

# Mod Properties
mod_version=0.1.0
maven_group=io.github.tunnelvisionmod
archives_base_name=TunnelVision

# Dependencies
fabric_version=0.155.3+26.1.2
moulconfig_version=4.7.2
modmenu_version=18.0.2
hypixel_modapi_version=1.0.2
hypixel_modapi_fabric_version=1.0.2+build.1+mc26.1
junit_version=6.1.3
